
const homeCareTips = [
  { tip: "Always boil or filter drinking water to prevent waterborne diseases." },
  { tip: "Wash hands with soap and water before eating and after using the toilet." },
  { tip: "Keep your house clean and free from stagnant water to avoid mosquito breeding." },
  { tip: "Ensure proper ventilation in sleeping areas to reduce respiratory infections." },
  { tip: "Use mosquito nets while sleeping to prevent malaria." },
  { tip: "Eat fresh fruits and vegetables to boost immunity." },
  { tip: "Store food in clean, covered containers to prevent contamination." },
  { tip: "Dispose of household waste properly to prevent pests and diseases." },
  { tip: "Take children for regular vaccinations, including measles and polio." },
  { tip: "Avoid overcrowding in sleeping areas to reduce the spread of infections." },
  { tip: "Practice safe cooking by thoroughly cooking meat and fish." },
  { tip: "Keep newborns warm and dry to prevent hypothermia." },
  { tip: "Breastfeed infants exclusively for the first six months." },
  { tip: "Keep sharp objects and chemicals out of children's reach." },
  { tip: "Use clean, safe toilets to prevent diarrheal diseases." },
  { tip: "Ensure regular handwashing in schools and homes." },
  { tip: "Trim bushes and keep the surroundings clean to reduce snake and insect bites." },
  { tip: "Use covered containers for storing water to prevent contamination." },
  { tip: "Seek medical care immediately if a child has persistent fever." },
  { tip: "Avoid using untreated surface water for drinking or cooking." },
  { tip: "Keep pets vaccinated and clean to prevent zoonotic diseases." },
  { tip: "Avoid sharing personal items like towels and toothbrushes." },
  { tip: "Store medicines safely and follow prescribed doses." },
  { tip: "Encourage children to play in safe, clean areas." },
  { tip: "Wash fruits and vegetables thoroughly before eating." },
  { tip: "Use clean cloth diapers or change disposable diapers regularly." },
  { tip: "Encourage regular exercise and outdoor activity for children." },
  { tip: "Cover your mouth and nose when coughing or sneezing." },
  { tip: "Boil or filter water when traveling to rural areas." },
  { tip: "Avoid exposure to smoke and indoor air pollution." },
  { tip: "Maintain personal hygiene to prevent skin infections." },
  { tip: "Teach children about handwashing and hygiene." },
  { tip: "Keep first aid kits at home for minor injuries." },
  { tip: "Store food at proper temperatures to prevent spoilage." },
  { tip: "Keep the kitchen and cooking areas clean." },
  { tip: "Avoid walking barefoot in areas with waste or contaminated soil." },
  { tip: "Practice safe waste disposal to prevent cholera outbreaks." },
  { tip: "Ensure safe water storage in barrels and tanks." },
  { tip: "Protect children from extreme heat by staying hydrated and using shade." },
  { tip: "Encourage breastfeeding mothers to maintain a nutritious diet." },
  { tip: "Keep windows and doors screened to prevent mosquito entry." },
  { tip: "Separate raw and cooked food to prevent cross-contamination." },
  { tip: "Avoid excessive sun exposure to prevent heat stroke." },
  { tip: "Teach children about safe hygiene habits early." },
  { tip: "Avoid eating street food that looks unhygienic." },
  { tip: "Clean latrines and toilets regularly." },
  { tip: "Ensure proper drainage around the home to prevent flooding." },
  { tip: "Use hand sanitizer when soap and water are not available." },
  { tip: "Wash bedding and clothes regularly." },
  { tip: "Avoid stagnant water around homes to prevent malaria." },
  { tip: "Do not give children leftover food that has spoiled." },
  { tip: "Encourage proper dental hygiene in children and adults." },
  { tip: "Keep small children away from open fires and hot surfaces." },
  { tip: "Report cases of infectious diseases to local health authorities." },
  { tip: "Encourage elderly family members to get vaccinated against influenza." },
  { tip: "Boil milk before giving it to infants or children." },
  { tip: "Use clean and safe utensils when preparing meals." },
  { tip: "Store grains and cereals in dry, pest-free areas." },
  { tip: "Avoid walking through floodwaters which may carry infections." },
  { tip: "Keep children's toys clean and disinfected regularly." },
  { tip: "Encourage regular bathing to maintain hygiene." },
  { tip: "Wash hands after handling money or public objects." },
  { tip: "Avoid drinking untreated river or pond water." },
  { tip: "Educate family members about mosquito breeding and malaria prevention." },
  { tip: "Cover wounds with clean bandages to prevent infection." },
  { tip: "Encourage proper nutrition during pregnancy and lactation." },
  { tip: "Use insect repellents in mosquito-prone areas." },
  { tip: "Keep floors and walls clean to prevent pests." },
  { tip: "Do not reuse disposable diapers or sanitary pads." },
  { tip: "Encourage safe play areas for children." },
  { tip: "Boil utensils and feeding bottles for infants." },
  { tip: "Ensure regular checkups for chronic conditions like diabetes and hypertension." },
  { tip: "Store medicines away from heat and sunlight." },
  { tip: "Ensure proper hygiene when preparing baby food." },
  { tip: "Avoid sharing drinks or food with people who are sick." },
  { tip: "Clean fruits and vegetables with safe water before cooking." },
  { tip: "Practice safe handling of poultry and livestock." },
  { tip: "Ensure proper ventilation in kitchens and bathrooms." },
  { tip: "Keep bedding and linens dry to prevent mold." },
  { tip: "Avoid smoking indoors, especially around children." },
  { tip: "Keep household chemicals out of reach of children." },
  { tip: "Use clean water when brushing teeth." },
  { tip: "Seek professional care for persistent cough or fever." },
  { tip: "Practice safe food storage to avoid spoilage." },
  { tip: "Use mosquito nets over children’s beds." },
  { tip: "Avoid overcrowding during outbreaks of respiratory infections." },
  { tip: "Encourage handwashing after playing outside." },
  { tip: "Keep toilets and washrooms sanitized." },
  { tip: "Dispose of dead animals safely to avoid disease spread." },
  { tip: "Keep the compound clean to avoid rodents and insects." },
  { tip: "Avoid walking barefoot in areas prone to injuries or infection." },
  { tip: "Teach children to sneeze or cough into elbows or tissues." },
  { tip: "Encourage nutritious meals rich in protein and vitamins." },
  { tip: "Ensure safe storage of drinking water in households." },
  { tip: "Avoid touching eyes, nose, or mouth with dirty hands." },
  { tip: "Use clean towels and washcloths for each family member." },
  { tip: "Avoid sharing sharp instruments or needles." },
  { tip: "Practice safe disposal of sanitary waste." },
  { tip: "Wash hands before handling infants." },
  { tip: "Keep the kitchen free from flies and pests." },
  { tip: "Boil or filter water from handpumps before drinking." },
  { tip: "Educate children on hygiene during school and home activities." },
  { tip: "Avoid leaving uncovered food to prevent contamination." },
  { tip: "Keep indoor areas clean to prevent respiratory issues." },
  { tip: "Encourage family members to exercise and stay active." },
  { tip: "Store grains and cereals in pest-free containers." },
  { tip: "Avoid swimming in contaminated rivers or ponds." },
];

export default homeCareTips